version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: es7.4.0-01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - path.repo=/usr/share/elasticsearch/es-backup
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/wyy/docker/data/elasticsearch7.4.0/es01/data:/usr/share/elasticsearch/data
      - /home/wyy/docker/data/elasticsearch7.4.0/es-backup:/usr/share/elasticsearch/es-backup
    ports:
      - 9200:9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: es7.4.0-02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - path.repo=/usr/share/elasticsearch/es-backup
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/wyy/docker/data/elasticsearch7.4.0/es02/data:/usr/share/elasticsearch/data
      - /home/wyy/docker/data/elasticsearch7.4.0/es-backup:/usr/share/elasticsearch/es-backup
    ports:
      - 9201:9200
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: es7.4.0-03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - path.repo=/usr/share/elasticsearch/es-backup
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/wyy/docker/data/elasticsearch7.4.0/es03/data:/usr/share/elasticsearch/data
      - /home/wyy/docker/data/elasticsearch7.4.0/es-backup:/usr/share/elasticsearch/es-backup
    ports:
      - 9202:9200      
